spring:
  datasource:
    url: jdbc:mysql://localhost:90/webenddb #localhost:3306
    username: root
    password: "070401"
    driver-class-name: com.mysql.cj.jdbc.Driver

config:
  jwt:
    token: IAmCool
    expire: 3600
    header: tokenks